<?php
/**
 * Oggetto web extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category   Default
 * @package    Oggetto
 * @copyright  Copyright © 2008–2011 Oggetto Web ltd (http://oggettoweb.com/)
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php $_product = $this->getProduct() ?>
<?php echo $this->getPriceHtml($_product, false, '_clone') ?>
<div class="add-to-cart">
    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
</div>
<div class="ajaxcart-cancel">
    <button id="cancel-bottom" type="button" title="<?php echo $this->__('Cancel') ?>" class="button btn-cart" onclick="hideOptionsDialog()"><span><span><?php echo $this->__('Close') ?></span></span></button>
</div>
</form>

